### ISSUE TITLE
how can my andriod phone connet to the node js server on my system.

### ISSUE THREAD

**Issue by akaelfty38** [pchab/ProjectRTC#10]
pls how can my andriod phone connet to the node js server on my system.and also the andriod app always open blank.

**Comment by pchab** [comment]
See [AndroidRTC issue#34](https://github.com/pchab/AndroidRTC/issues/34).
If nothing happen when you open the AndroidRTC app, it usually means that it could not connect to the server. You need to change the address in strings.xml to the IP of your ProjectRTC server (obvisously localhost won't work).

**Comment by akaelfty38** [comment]
thanks works fine now

**Comment by Dildarkhan** [comment]
If you want to connect android app to local host, updated your android app string file as follows to specify local host ip and port no.

IP Address : 10.0.2.2
Port No: 3000

Try for this.
Thanks
