### ISSUE TITLE
Doesn't work when ported to public IP. Works on local host

### ISSUE THREAD

**Issue by groversachin** [pchab/ProjectRTC#6]
When project RTC is installed on public server node.js. Clients connect but the live streaming stops to function. Tried it on google stun. Created custom turn server with and without credentials (turnserver). Tried it on custom stun server (Stuntman).

**Comment by azfarsiddiqui** [comment]
@groversachin, I have run into the exact same problem. Were you able to resolve it? I have also setup a turn server but the output is still the same.

**Comment by azfarsiddiqui** [comment]
@pchab, any clues about this?

**Comment by pchab** [comment]
I can't seem to reproduced this issue. You can test on my server (public ip http://ns37269.ip-91-121-3.eu:3000/)
