### ISSUE TITLE
Camera and Microphone are opened but not streaming

### ISSUE THREAD

**Issue by olyjosh** [pchab/ProjectRTC#8]
After successfully running using "node app.js". I tried to use browser to browser communication but there isn't anything streaming in any of the browsers on the two devices I'm trying to use. Though I was able to copy the links giving to me on clicking start and this fire up browser permissions for camera and microphone and I can only see my self at the top-right part of the page but no part of the page is showing stream from other user(device).

**Comment by pchab** [comment]
What browser did you use ?

**Comment by olyjosh** [comment]
Both Chrome and Firefox

**Comment by pchab** [comment]
Are you trying to access the camera with 2 browsers on the same computer ? (chrome calling firefox or the other way around) : It is not possible.
Can you take a look at the console log ? (right click on the page, choose "inspect element", and look at the console)

**Comment by olyjosh** [comment]
No, it's two different devices over wireless. I will check the console and get back

**Comment by olyjosh** [comment]
This is what the error is like in the browser's console 

Use of getPreventDefault() is deprecated.  Use defaultPrevented instead.          jquery-1.7.1.min.js:3:0

Mandatory/optional in createOffer options is deprecated! Use {"offerToReceiveAudio":true,"offerToReceiveVideo":true} instead (note the case difference)! <unknown>
"received init from Ggo4U1YRoLJ4p5yzv_A0"           RTCclient.js:97:4
setLocalDescription called without success/failure callbacks. This is deprecated, and will be an error in the future. <unknown>
"sending offer to Ggo4U1YRoLJ4p5yzv_A0"          RTCclient.js:123:4
"sending candidate to Ggo4U1YRoLJ4p5yzv_A0"

**Comment by pchab** [comment]
Hi,
Can you try again with the latest version of projectRtc ?

**Comment by olyjosh** [comment]
With the latest version, It all work fine. 
Welldone

**Comment by Bala206** [comment]
In streams list Random unique id returned.Which file contain this?
Which is base for  RandomId generation?

help me?

**Comment by Bala206** [comment]
@olyjosh In streams list Random unique id returned.Which file contain this?
Which is base for  RandomId generation?

help me?
